### ISSUE TITLE
Letsencrypt support uses deprecated ACMEv1 protocol

### ISSUE THREAD

**Issue by jgrgt** [louketo/louketo-proxy#523] opened 2020-04-07 08:43 UTC
Running quay.io/keycloak/keycloak-gatekeeper:9.0.2 and enabling letsencrypt gives:

```
2020/04/07 08:19:27 http: TLS handshake error from xxxx:xxxx: 403 urn:acme:error:unauthorized: Account creation on ACMEv1 is disabled. Please upgrade your ACME client to a version that supports ACMEv2 / RFC 8555. See https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430 for details.
```

Meaning the letsencrypt support is no longer working now.

**Comment by ThoreKr** [comment] 2020-04-12 01:54
This can be partially resolved by upgrading `golang.org/x/crypto`.

Unfortunately just this is not sufficient. As TLS-SNI-01 has been deprecated the default autocert behaviour does not work any more.
Instead another challenge type has to be supported. As far as I've understood the http01 challenge needs to use the `HTTPHandler` provided by the manager [see here](https://github.com/drone/drone/pull/2301/files). When trying to set up something similar the whole gateway just gets stuck.

Most likely requests to `http://<YOUR_DOMAIN>/.well-known/acme-challenge/<TOKEN>` [source](https://letsencrypt.org/docs/challenge-types/) need to be routed differently.

**Comment by abstractj** [comment] 2020-05-18 15:10
@ThoreKr thanks for pointing that out. @jgrgt for now, I'm closing this issue as a duplicate of #570.

**Closed by abstractj** 2020-05-18 15:10 UTC
