### ISSUE TITLE
Gatekeeper sidecar container crashing with SIGPIPE on first HTTP request

### ISSUE THREAD

**Issue by PastNullInfinity** [louketo/louketo-proxy#623] opened 2020-05-25 13:27 UTC
I'm currently running Gatekeeper version 9.0.0 as a sidecar container inside a Kubernets cluster. My setup includes the use of a slightly custom [ProxyInjector](https://github.com/stakater/ProxyInjector) controller, that has the function of creating the sidecar with Gatekeeper for Deployments that need them.

The configuration (for a Kibana dashboard) is as follows (ignore the `authproxy.stakater` prefix, as it is just a way to inject the cli arguments into the Gatekeeper sidecar):

```yaml
    authproxy.stakater.com/enabled: "true"
    authproxy.stakater.com/discovery-url: "https://keycloak.XXXXX.com/auth/realms/master"
    authproxy.stakater.com/resources: "uri=/*|roles=admin"
    authproxy.stakater.com/scope: "openid email"
    authproxy.stakater.com/listen: "0.0.0.0:8080"
    authproxy.stakater.com/redirection-url: kibana.XXXXX.com
    authproxy.stakater.com/upstream-url: "http://127.0.0.1:5601"
```

With this setup, Gatekeeper crashes at the very first HTTP GET request, with a SIGPIPE, I'm including the `strace` output (I've cut it in order to include only the crash portion ,as there's a lot of junk about mutex lock and unlock)

```
bash-4.4# strace -fp 7
strace: Process 7 attached with 9 threads
----------
[pid    15] <... accept4 resumed> {sa_family=AF_INET6, sin6_port=htons(41772), inet_pton(AF_INET6, "::ffff:127.0.0.1", &sin6_addr), sin6_flowinfo=htonl(0), sin6_scope_id=0}, [112->28], SOCK_CLOEXEC|SOCK_NONBLOCK) = 6
[pid    15] epoll_ctl(4, EPOLL_CTL_ADD, 6, {EPOLLIN|EPOLLOUT|EPOLLRDHUP|EPOLLET, {u32=3639160160, u64=140380350262624}}) = 0
[pid     9] <... nanosleep resumed> NULL) = 0
[pid    15] getsockname(6, {sa_family=AF_INET6, sin6_port=htons(8080), inet_pton(AF_INET6, "::ffff:127.0.0.1", &sin6_addr), sin6_flowinfo=htonl(0), sin6_scope_id=0}, [112->28]) = 0
[pid     9] nanosleep({tv_sec=0, tv_nsec=20000},  <unfinished ...>
[pid    15] setsockopt(6, SOL_TCP, TCP_NODELAY, [1], 4) = 0
[pid    15] futex(0xf1bb60, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
--------------
[pid    12] futex(0xc0000d2f40, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid    10] futex(0xf1efe0, FUTEX_WAIT_PRIVATE, 0, {tv_sec=9, tv_nsec=999905848} <unfinished ...>
[pid     9] nanosleep({tv_sec=0, tv_nsec=20000},  <unfinished ...>
[pid     7] epoll_pwait(4,  <unfinished ...>
[pid    15] <... read resumed> "GET / HTTP/1.1\r\nhost: kibana.XX"..., 4096) = 758
[pid     9] <... nanosleep resumed> NULL) = 0
[pid     9] nanosleep({tv_sec=0, tv_nsec=20000},  <unfinished ...>
[pid    15] futex(0xf1efe0, FUTEX_WAKE_PRIVATE, 1) = 1
[pid    10] <... futex resumed> )       = 0
[pid    15] futex(0xc0000d2f40, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
[pid    10] futex(0xc0000464c0, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid     9] <... nanosleep resumed> NULL) = 0
[pid    15] <... futex resumed> )       = 1
[pid    12] <... futex resumed> )       = 0
[pid     9] nanosleep({tv_sec=0, tv_nsec=20000},  <unfinished ...>
[pid    12] futex(0xc0000464c0, FUTEX_WAKE_PRIVATE, 1) = 1
[pid    12] futex(0xf1efe0, FUTEX_WAIT_PRIVATE, 0, {tv_sec=9, tv_nsec=999791508} <unfinished ...>
[pid    15] write(1, "[cors] 2020/05/20 16:50:34 Handl"..., 51 <unfinished ...>
[pid    10] <... futex resumed> )       = 0
[pid    15] <... write resumed> )       = -1 EPIPE (Broken pipe)
[pid    10] read(6,  <unfinished ...>
[pid    15] --- SIGPIPE {si_signo=SIGPIPE, si_code=SI_USER, si_pid=7, si_uid=0} ---
[pid     9] <... nanosleep resumed> NULL) = 0
[pid    15] rt_sigreturn({mask=[]} <unfinished ...>
[pid     9] nanosleep({tv_sec=0, tv_nsec=20000},  <unfinished ...>
[pid    15] <... rt_sigreturn resumed> ) = -1 EPIPE (Broken pipe)
[pid    10] <... read resumed> 0xc000240461, 1) = -1 EAGAIN (Resource temporarily unavailable)
[pid    15] rt_sigprocmask(SIG_UNBLOCK, [PIPE],  <unfinished ...>
[pid    10] futex(0xc0000464c0, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid    15] <... rt_sigprocmask resumed> NULL, 8) = 0
[pid     9] <... nanosleep resumed> NULL) = 0
[pid    15] gettid( <unfinished ...>
----------------------------------
[pid    10] <... futex resumed>)        = ?
[pid    11] +++ killed by SIGPIPE +++
[pid    10] +++ killed by SIGPIPE +++
[pid     9] +++ killed by SIGPIPE +++
<... epoll_pwait resumed> <unfinished ...>) = ?
```

I'm kind of out of options in troubleshooting: I've already ruled out other processes interfering with Gatekeeper's socket, possible issues with CORS, problems arising from the way the Ingress to the Service is set up (this crash happens even with a port-forward directly into the Pod).  I'm happy to provide any additional info that I might have forgot to add.

**Comment by PastNullInfinity** [comment] 2020-05-27 09:17
An update. 

We've figured out that the culprit in these crashes is the launch of Gatekeeper with the `--resources` argument being inproperly quoted. This is an expected behaviour I assume (in the docs the resources option is always set with quotes ), although it would be nice to throw a more explicit exception when this happens, instead of crashing silently.

**Comment by abstractj** [comment] 2020-05-28 21:27
@PastNullInfinity thanks for reporting this issue and providing some feedback about Louketo. I'm closing this issue, because as you already mentioned, this is not a bug. For enhancements and feature requests, please create a new issue.

**Closed by abstractj** 2020-05-28 21:27 UTC
